/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/utils/ThemeColors`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/ThemeColors`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/Collapsible${`?${string}` | `#${string}` | ''}` | `/components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/components/HapticTab${`?${string}` | `#${string}` | ''}` | `/components/ThemedText${`?${string}` | `#${string}` | ''}` | `/components/ThemedView${`?${string}` | `#${string}` | ''}` | `/components/ui/IconSymbol${`?${string}` | `#${string}` | ''}` | `/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/utils/ThemeColors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/utils/ThemeColors`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
